In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_parquet('/home/rproner/Documents/Data/MacroAtRisk/processed/us_4q_iar_x.parquet')
df.head()

            Infl_yoy_avg_12m  EXPINF10YR      ugap  Oil_infl_yoy  gz_spread
date
1973-01-01          0.041451    3.022789 -0.009940           0.0        NaN
1973-02-01          0.039837    3.029892 -0.215299           0.0        NaN
1973-03-01          0.039066    3.076057 -0.320328           0.0        NaN
1973-04-01          0.038313    3.072506 -0.225691           0.0        NaN
1973-05-01          0.037780    3.115120 -0.330866           0.0        NaN

In [12]:
y = pd.read_parquet('/home/rproner/Documents/Data/MacroAtRisk/processed/us_4q_fred_y.parquet')
y.head()

            Infl_yoy    IP_yoy  Unrate_yoy
date
1961-01-01  0.015876 -0.088327    0.238411
1961-02-01  0.014515 -0.080604    0.362905
1961-03-01  0.014515 -0.065519    0.245122
1961-04-01  0.009099 -0.037214    0.297252
1961-05-01  0.009089 -0.020786    0.330854

In [6]:
df.loc['1974-02-01':, :].shape, y.loc['1974-02-01':, :].shape

((612, 5), (611, 3))

In [7]:
df.loc['1974-02-01':, :]

            Infl_yoy_avg_12m  EXPINF10YR      ugap  Oil_infl_yoy  gz_spread
1974-02-01          0.032520    3.211002 -1.176807      0.000000   1.075493
1974-03-01          0.032605    3.274923 -1.081367      0.000000   1.029968
1974-04-01          0.033670    3.299781 -1.186335      0.000000   0.982746
1974-05-01          0.035115    3.285576 -1.091046      0.000000   1.046494
1974-06-01          0.036953    3.349498 -1.195836      0.000000   1.185926
...                      ...         ...       ...           ...        ...
2024-08-01          0.056847    2.064013 -0.837078     -0.140526   1.345703
2024-09-01          0.053309    2.138766 -0.635228      0.059549   1.334470
2024-10-01          0.049761    2.222218 -0.533394     -0.022058   1.429122
2024-11-01          0.046197    2.362663 -0.431452     -0.082485   1.193516
2024-12-01          0.043033    2.384114 -0.629525     -0.061230   1.143008

[612 rows x 5 columns]

In [8]:
y.loc['1974-02-01':, :]

            Infl_yoy    IP_yoy  Unrate_yoy
date
1974-02-01  0.095310  0.017596    0.039221
1974-03-01  0.096566  0.017148    0.040005
1974-04-01  0.095934  0.015701    0.019803
1974-05-01  0.101709  0.016802    0.040005
1974-06-01  0.103096  0.013689    0.097164
...              ...       ...         ...
2024-08-01  0.025774 -0.004058    0.126752
2024-09-01  0.024034 -0.012077    0.075986
2024-10-01  0.025389 -0.009997    0.050010
2024-11-01  0.026780 -0.015702    0.126752
2024-12-01  0.028319 -0.002745    0.075986

[611 rows x 3 columns]

In [8]:
df.loc['1982-01-01']

Infl_yoy_avg_12m    0.126849
EXPINF10YR          5.476654
ugap                1.013801
Oil_infl_yoy        0.156346
gz_spread           1.148932
Name: 1982-01-01 00:00:00, dtype: float64

In [13]:
for yr in df.index:
    if yr not in y.index:
        print(yr)

In [14]:
df.index.value_counts()

1982-01-01    2
2008-01-01    1
2007-06-01    1
2007-07-01    1
2007-08-01    1
             ..
1990-06-01    1
1990-07-01    1
1990-08-01    1
1990-09-01    1
2024-12-01    1
Name: count, Length: 624, dtype: int64

In [9]:
df.index[df.index != y.index]

ValueError: Lengths must match to compare